#!/usr/bin/env tsx

import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import type { SharedBitInventoryEntry, SharedBitRegistryItem } from '../src/catalog/contracts';

type ParsedBitMetadata = {
  name: string;
  description: string;
  tags: string[];
  duration: number;
  width?: number;
  height?: number;
  registry: SharedBitRegistryItem;
};

const projectRoot = fileURLToPath(new URL('..', import.meta.url));
const examplesRoot = path.join(projectRoot, 'docs', 'src', 'bits', 'examples');
const generatedTsPath = path.join(projectRoot, 'src', 'catalog', 'inventory.generated.ts');
const generatedJsonPath = path.join(projectRoot, 'src', 'catalog', 'inventory.generated.json');

const GENERATED_BANNER = [
  '/* eslint-disable */',
  '// This file is generated by scripts/generate-shared-bit-inventory.ts.',
  '// Do not edit it manually.',
  '',
].join('\n');

const normalizePath = (value: string): string => value.split(path.sep).join('/');

const listTsxFiles = async (dirPath: string): Promise<string[]> => {
  const entries = await readdir(dirPath, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dirPath, entry.name);

      if (entry.isDirectory()) {
        return listTsxFiles(fullPath);
      }

      if (entry.isFile() && entry.name.endsWith('.tsx')) {
        return [fullPath];
      }

      return [] as string[];
    })
  );

  return files.flat().sort((left, right) => left.localeCompare(right));
};

const extractObjectLiteral = (sourceCode: string, declaration: string): string => {
  const declarationIndex = sourceCode.indexOf(declaration);

  if (declarationIndex === -1) {
    throw new Error(`Missing declaration: ${declaration}`);
  }

  const afterDeclaration = sourceCode.slice(declarationIndex + declaration.length);
  const openingIndex = afterDeclaration.indexOf('{');

  if (openingIndex === -1) {
    throw new Error(`Declaration is missing an opening brace: ${declaration}`);
  }

  let depth = 0;
  let closingIndex = -1;

  for (let index = openingIndex; index < afterDeclaration.length; index += 1) {
    const character = afterDeclaration[index];

    if (character === '{') {
      depth += 1;
    }

    if (character === '}') {
      depth -= 1;
      if (depth === 0) {
        closingIndex = index;
        break;
      }
    }
  }

  if (closingIndex === -1) {
    throw new Error(`Declaration is missing a closing brace: ${declaration}`);
  }

  return afterDeclaration.slice(openingIndex, closingIndex + 1);
};

const parseMetadataObject = (sourceCode: string): ParsedBitMetadata => {
  const metadataLiteral = extractObjectLiteral(sourceCode, 'export const metadata =')
    .replace(/\s+as\s+const/g, '')
    .replace(/\s+satisfies\s+[A-Za-z0-9_$.<>]+/g, '');

  return Function(`return (${metadataLiteral});`)() as ParsedBitMetadata;
};

const assertComponentExport = (sourceCode: string, relativePath: string): void => {
  const hasComponentExport =
    /export\s+const\s+Component\b/.test(sourceCode) ||
    /export\s+function\s+Component\b/.test(sourceCode);

  if (!hasComponentExport) {
    throw new Error(`Bit file is missing an exported Component: ${relativePath}`);
  }
};

const assertMetadata = (metadata: ParsedBitMetadata, relativePath: string): void => {
  if (typeof metadata.name !== 'string' || metadata.name.trim().length === 0) {
    throw new Error(`Bit metadata.name must be a non-empty string: ${relativePath}`);
  }

  if (typeof metadata.description !== 'string' || metadata.description.trim().length === 0) {
    throw new Error(`Bit metadata.description must be a non-empty string: ${relativePath}`);
  }

  if (!Array.isArray(metadata.tags) || metadata.tags.some((tag) => typeof tag !== 'string')) {
    throw new Error(`Bit metadata.tags must be a string array: ${relativePath}`);
  }

  if (typeof metadata.duration !== 'number' || !Number.isFinite(metadata.duration)) {
    throw new Error(`Bit metadata.duration must be a number: ${relativePath}`);
  }

  if (!metadata.registry || typeof metadata.registry !== 'object') {
    throw new Error(`Bit metadata.registry is required: ${relativePath}`);
  }

  if (typeof metadata.registry.name !== 'string' || metadata.registry.name.trim().length === 0) {
    throw new Error(`Bit metadata.registry.name must be a non-empty string: ${relativePath}`);
  }

  if (typeof metadata.registry.title !== 'string' || metadata.registry.title.trim().length === 0) {
    throw new Error(`Bit metadata.registry.title must be a non-empty string: ${relativePath}`);
  }

  if (
    typeof metadata.registry.description !== 'string' ||
    metadata.registry.description.trim().length === 0
  ) {
    throw new Error(`Bit metadata.registry.description must be a non-empty string: ${relativePath}`);
  }

  if (metadata.registry.type !== 'bit') {
    throw new Error(`Bit metadata.registry.type must equal "bit": ${relativePath}`);
  }

  if (
    metadata.registry.add !== 'when-needed' &&
    metadata.registry.add !== 'when-added'
  ) {
    throw new Error(`Bit metadata.registry.add must be a supported registry add mode: ${relativePath}`);
  }

  if (
    !Array.isArray(metadata.registry.registryDependencies) ||
    metadata.registry.registryDependencies.some((dependency) => typeof dependency !== 'string')
  ) {
    throw new Error(`Bit metadata.registry.registryDependencies must be a string array: ${relativePath}`);
  }

  if (
    !Array.isArray(metadata.registry.dependencies) ||
    metadata.registry.dependencies.some((dependency) => typeof dependency !== 'string')
  ) {
    throw new Error(`Bit metadata.registry.dependencies must be a string array: ${relativePath}`);
  }

  if (!Array.isArray(metadata.registry.files) || metadata.registry.files.length !== 1) {
    throw new Error(`Bit metadata.registry.files must contain exactly one source file: ${relativePath}`);
  }

  if (metadata.registry.files[0]?.path !== relativePath) {
    throw new Error(
      `Bit metadata.registry.files[0].path must match the defining file path (${relativePath}): ${relativePath}`
    );
  }
};

const toInventoryEntry = (filePath: string, metadata: ParsedBitMetadata): SharedBitInventoryEntry => {
  const relativePath = normalizePath(path.relative(projectRoot, filePath));
  const exportName = path.basename(filePath, path.extname(filePath));

  return {
    exportName,
    id: metadata.registry.name,
    name: metadata.name,
    description: metadata.description,
    tags: [...metadata.tags],
    duration: metadata.duration,
    width: metadata.width,
    height: metadata.height,
    sourcePath: relativePath,
    componentNames: ['Component'],
    registryDependencies: [...metadata.registry.registryDependencies],
    registry: {
      name: metadata.registry.name,
      title: metadata.registry.title,
      description: metadata.registry.description,
      type: 'bit',
      add: metadata.registry.add,
      registryDependencies: [...metadata.registry.registryDependencies],
      dependencies: [...metadata.registry.dependencies],
      files: [{ path: relativePath }],
    },
  };
};

const assertUniqueEntries = (entries: SharedBitInventoryEntry[]): void => {
  const seenIds = new Map<string, string>();
  const seenExports = new Map<string, string>();
  const seenSourcePaths = new Set<string>();

  for (const entry of entries) {
    const existingIdPath = seenIds.get(entry.id);
    if (existingIdPath) {
      throw new Error(`Duplicate bit id "${entry.id}" in ${existingIdPath} and ${entry.sourcePath}`);
    }

    const existingExportPath = seenExports.get(entry.exportName);
    if (existingExportPath) {
      throw new Error(
        `Duplicate exportName "${entry.exportName}" in ${existingExportPath} and ${entry.sourcePath}`
      );
    }

    if (seenSourcePaths.has(entry.sourcePath)) {
      throw new Error(`Duplicate sourcePath "${entry.sourcePath}" in generated inventory.`);
    }

    seenIds.set(entry.id, entry.sourcePath);
    seenExports.set(entry.exportName, entry.sourcePath);
    seenSourcePaths.add(entry.sourcePath);
  }
};

const renderInventoryModule = (entries: SharedBitInventoryEntry[]): string =>
  [
    GENERATED_BANNER,
    "import type { SharedBitInventoryEntry } from './contracts';",
    '',
    `export const sharedBitInventory = ${JSON.stringify(entries, null, 2)} as const satisfies readonly SharedBitInventoryEntry[];`,
    '',
    'export const sharedBitInventoryCount = sharedBitInventory.length;',
    '',
  ].join('\n');

export const generateSharedBitInventory = async (): Promise<SharedBitInventoryEntry[]> => {
  const bitFiles = await listTsxFiles(examplesRoot);
  const entries: SharedBitInventoryEntry[] = [];

  for (const filePath of bitFiles) {
    const relativePath = normalizePath(path.relative(projectRoot, filePath));
    const sourceCode = await readFile(filePath, 'utf8');

    assertComponentExport(sourceCode, relativePath);

    const metadata = parseMetadataObject(sourceCode);
    assertMetadata(metadata, relativePath);
    entries.push(toInventoryEntry(filePath, metadata));
  }

  assertUniqueEntries(entries);

  await mkdir(path.dirname(generatedTsPath), { recursive: true });
  await writeFile(generatedTsPath, renderInventoryModule(entries));
  await writeFile(generatedJsonPath, `${JSON.stringify(entries, null, 2)}\n`);

  return entries;
};

const main = async (): Promise<void> => {
  const entries = await generateSharedBitInventory();
  console.log(`Generated shared bit inventory with ${entries.length} bit(s).`);
};

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}