import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';

// Barrel-management for the install step.
//
// After `ondajs add` writes component (and/or transition) files, this
// module updates a barrel at `<componentsOut>/index.ts` that re-exports
// installed entries as two parallel registries:
//
//   • `ondaRegistry`    — components keyed by PascalCase name. Shape
//                         `{ component, schema }`. The exact shape
//                         `<CompositionRenderer registry={...}>` expects.
//   • `ondaTransitions` — transitions keyed by camelCase factory name.
//                         Shape `{ factory, schema }`. Transitions are
//                         factories (not React components) so they
//                         can't share the component registry shape —
//                         mirrors the split in `lib/registry-summary.ts`.
//
// Why a sidecar `.ondajs-installed.json` instead of parsing the barrel:
// parsing TypeScript to extract existing entries is fragile and pulls
// in a parser dep. The sidecar is the canonical state; the barrel is
// generated from it. If a user manually edits the barrel without the
// CLI knowing, the next install regenerates from the sidecar (which
// the CLI controls) — manual edits are simply lost. To opt out, pass
// `--no-barrel` or delete the sidecar and the CLI skips with a warning.
//
// Safety contract:
//   - If the barrel exists but the sidecar doesn't, the CLI assumes
//     the user wrote the barrel by hand. It refuses to clobber and
//     prints a warning so the user can either delete the barrel
//     (CLI takes over) or pass `--no-barrel` (CLI never touches it).
//   - The barrel carries a header comment marking it CLI-managed.

const BARREL_HEADER = `// AUTO-GENERATED by \`ondajs add\` — do not edit manually.
// Re-run \`bunx ondajs add <slug>\` to update.
// Pass \`--no-barrel\` to opt out; delete this file + .ondajs-installed.json
// to disable barrel management going forward.
`;

const SIDECAR_FILENAME = '.ondajs-installed.json';
const BARREL_FILENAME = 'index.ts';

/**
 * A single installed component's barrel entry — what the barrel imports
 * and re-exports.
 */
export type InstalledComponent = {
  /** Slug (kebab-case, e.g. `"blur-reveal"`). */
  slug: string;
  /** Component name (PascalCase, the React component export). */
  componentName: string;
  /** Schema name (camelCase + `Schema`, e.g. `"blurRevealSchema"`). */
  schemaName: string;
  /**
   * Import path relative to the barrel file. Computed once at install
   * time so the barrel imports work regardless of where the consumer
   * moves their `componentsOut` directory later.
   */
  importPath: string;
};

/**
 * A single installed transition's barrel entry. Transitions are
 * presentation factories (not React components), so the shape differs
 * from {@link InstalledComponent}: the named export is camelCase
 * (`crossFade`, not `CrossFade`) and the import path includes the
 * `transitions/` sub-folder the CLI writes to.
 */
export type InstalledTransition = {
  /** Slug (kebab-case, e.g. `"cross-fade"`). */
  slug: string;
  /** Factory name (camelCase, the function export — e.g. `"crossFade"`). */
  factoryName: string;
  /** Schema name (camelCase + `Schema`, e.g. `"crossFadeSchema"`). */
  schemaName: string;
  /** Import path relative to the barrel file (includes `transitions/`). */
  importPath: string;
};

type Sidecar = {
  components: InstalledComponent[];
  /** Optional for back-compat — older sidecars predate transition support. */
  transitions?: InstalledTransition[];
};

export type BarrelOutcome =
  | { kind: 'written'; path: string; componentCount: number; transitionCount: number }
  | { kind: 'unchanged'; path: string; componentCount: number; transitionCount: number }
  | { kind: 'skipped-foreign'; path: string }
  | { kind: 'disabled' };

/**
 * Derive the PascalCase component name and `${camelCase}Schema` name from
 * a slug. Standard kebab → Pascal/camel transformation; the catalog's
 * Zod-schema naming convention is `${camelCaseSlug}Schema` (e.g.
 * `blurRevealSchema`, `titleCardSchema`).
 */
export function namesFromSlug(slug: string): {
  componentName: string;
  schemaName: string;
} {
  const parts = slug.split('-').filter(Boolean);
  const pascal = parts.map((p) => p[0].toUpperCase() + p.slice(1)).join('');
  const camel = pascal[0].toLowerCase() + pascal.slice(1);
  return {
    componentName: pascal,
    schemaName: `${camel}Schema`,
  };
}

/**
 * Like {@link namesFromSlug} but for transition factories — the named
 * export is camelCase (`crossFade`), not PascalCase. Mirrors the
 * registry convention (`registry/transitions/cross-fade/crossFade.tsx`).
 */
export function transitionNamesFromSlug(slug: string): {
  factoryName: string;
  schemaName: string;
} {
  const parts = slug.split('-').filter(Boolean);
  const pascal = parts.map((p) => p[0].toUpperCase() + p.slice(1)).join('');
  const camel = pascal[0].toLowerCase() + pascal.slice(1);
  return {
    factoryName: camel,
    schemaName: `${camel}Schema`,
  };
}

/**
 * Compute the import path the barrel uses for a given component slug.
 * The barrel sits at `<componentsOut>/index.ts`; the component lives at
 * `<componentsOut>/<slug>/<ComponentName>.tsx`.
 */
function importPathFromSlug(slug: string, componentName: string): string {
  return `./${slug}/${componentName}`;
}

/**
 * Compute the import path the barrel uses for a given transition slug.
 * The barrel sits at `<componentsOut>/index.ts`; the transition factory
 * lives at `<componentsOut>/transitions/<slug>/<factoryName>.tsx` (the
 * extra `transitions/` segment matches how `ondajs add` writes them).
 */
function transitionImportPathFromSlug(slug: string, factoryName: string): string {
  return `./transitions/${slug}/${factoryName}`;
}

function sidecarPath(componentsOut: string): string {
  return resolve(componentsOut, SIDECAR_FILENAME);
}

function barrelPath(componentsOut: string): string {
  return resolve(componentsOut, BARREL_FILENAME);
}

function readSidecar(componentsOut: string): Sidecar | null {
  const path = sidecarPath(componentsOut);
  if (!existsSync(path)) return null;
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as unknown;
    if (
      typeof parsed === 'object' &&
      parsed !== null &&
      'components' in parsed &&
      Array.isArray((parsed as Sidecar).components)
    ) {
      return parsed as Sidecar;
    }
  } catch {
    // Malformed sidecar — treat as missing; we'll rebuild from scratch.
  }
  return null;
}

function isBarrelManaged(componentsOut: string): boolean {
  const path = barrelPath(componentsOut);
  if (!existsSync(path)) return true; // No barrel = we're free to create one.
  const existing = readFileSync(path, 'utf8');
  return existing.startsWith('// AUTO-GENERATED by `ondajs add`');
}

/**
 * Merge a list of newly-installed entries into the existing sidecar
 * (deduped by slug — re-installing doesn't duplicate). Returns the
 * merged list in alphabetical order (predictable for diffs).
 */
function mergeBySlug<T extends { slug: string }>(existing: T[], added: T[]): T[] {
  const map = new Map<string, T>();
  for (const c of existing) map.set(c.slug, c);
  for (const c of added) map.set(c.slug, c); // Newly-installed wins on conflict.
  return [...map.values()].sort((a, b) => a.slug.localeCompare(b.slug));
}

/**
 * Build the barrel file content from the installed components and
 * transitions. Two registries side-by-side; omits the transitions
 * registry entirely when no transitions are installed so existing
 * component-only projects' barrels stay byte-identical (back-compat).
 */
function renderBarrel(
  components: InstalledComponent[],
  transitions: InstalledTransition[],
): string {
  if (components.length === 0 && transitions.length === 0) {
    return `${BARREL_HEADER}\nexport const ondaRegistry = {} as const;\n`;
  }

  const componentImports = components
    .map(
      (c) =>
        `import { ${c.componentName}, ${c.schemaName} } from '${c.importPath}';`,
    )
    .join('\n');

  const transitionImports = transitions
    .map(
      (t) =>
        `import { ${t.factoryName}, ${t.schemaName} } from '${t.importPath}';`,
    )
    .join('\n');

  const componentEntries = components
    .map(
      (c) =>
        `  ${c.componentName}: { component: ${c.componentName}, schema: ${c.schemaName} },`,
    )
    .join('\n');

  const transitionEntries = transitions
    .map(
      (t) =>
        `  ${t.factoryName}: { factory: ${t.factoryName}, schema: ${t.schemaName} },`,
    )
    .join('\n');

  const allImports = [componentImports, transitionImports].filter(Boolean).join('\n');

  const componentBlock = `export const ondaRegistry = {${
    componentEntries ? '\n' + componentEntries + '\n' : ''
  }} as const;\n`;

  const transitionBlock =
    transitions.length > 0
      ? `\nexport const ondaTransitions = {\n${transitionEntries}\n} as const;\n`
      : '';

  return `${BARREL_HEADER}
${allImports}

${componentBlock}${transitionBlock}`;
}

/**
 * Update (or create) the barrel + sidecar for a freshly-completed install.
 *
 * @param componentsOut Absolute path to the components directory the CLI just wrote to.
 * @param installedComponentSlugs Component slugs the install touched (file targets at `components/onda/<slug>/…`). Lib helpers and transitions are excluded by the caller.
 * @param installedTransitionSlugs Transition slugs the install touched (file targets at `components/onda/transitions/<slug>/…`).
 * @param options.dryRun  When true, computes the outcome but doesn't write files.
 * @param options.cwd     For pretty-printing relative paths in the outcome message.
 */
export function updateBarrel(
  componentsOut: string,
  installedComponentSlugs: string[],
  installedTransitionSlugs: string[],
  options: { dryRun: boolean; cwd: string },
): BarrelOutcome {
  // Refuse to clobber a user-written barrel (existing barrel without the
  // CLI marker comment). User opts in either by deleting their barrel or
  // by passing --no-barrel (handled at the caller).
  if (!isBarrelManaged(componentsOut)) {
    return { kind: 'skipped-foreign', path: barrelPath(componentsOut) };
  }

  // Build entry rows for the newly-installed slugs.
  const addedComponents: InstalledComponent[] = installedComponentSlugs.map((slug) => {
    const { componentName, schemaName } = namesFromSlug(slug);
    return {
      slug,
      componentName,
      schemaName,
      importPath: importPathFromSlug(slug, componentName),
    };
  });

  const addedTransitions: InstalledTransition[] = installedTransitionSlugs.map((slug) => {
    const { factoryName, schemaName } = transitionNamesFromSlug(slug);
    return {
      slug,
      factoryName,
      schemaName,
      importPath: transitionImportPathFromSlug(slug, factoryName),
    };
  });

  // Merge with whatever's already tracked in the sidecar.
  const existing = readSidecar(componentsOut);
  const mergedComponents = mergeBySlug(existing?.components ?? [], addedComponents);
  const mergedTransitions = mergeBySlug(existing?.transitions ?? [], addedTransitions);

  const newBarrel = renderBarrel(mergedComponents, mergedTransitions);
  // Only emit the `transitions` sidecar field once we actually have any —
  // keeps old component-only sidecars byte-identical (back-compat).
  const sidecarPayload: Sidecar =
    mergedTransitions.length > 0
      ? { components: mergedComponents, transitions: mergedTransitions }
      : { components: mergedComponents };
  const newSidecar = JSON.stringify(sidecarPayload, null, 2) + '\n';

  const bPath = barrelPath(componentsOut);
  const sPath = sidecarPath(componentsOut);

  // Idempotency: if both files exist with identical content, no-op.
  const barrelUnchanged =
    existsSync(bPath) && readFileSync(bPath, 'utf8') === newBarrel;
  const sidecarUnchanged =
    existsSync(sPath) && readFileSync(sPath, 'utf8') === newSidecar;

  if (barrelUnchanged && sidecarUnchanged) {
    return {
      kind: 'unchanged',
      path: bPath,
      componentCount: mergedComponents.length,
      transitionCount: mergedTransitions.length,
    };
  }

  if (options.dryRun) {
    return {
      kind: 'written',
      path: bPath,
      componentCount: mergedComponents.length,
      transitionCount: mergedTransitions.length,
    };
  }

  mkdirSync(dirname(bPath), { recursive: true });
  writeFileSync(bPath, newBarrel, 'utf8');
  writeFileSync(sPath, newSidecar, 'utf8');

  return {
    kind: 'written',
    path: bPath,
    componentCount: mergedComponents.length,
    transitionCount: mergedTransitions.length,
  };
}

/**
 * Format a barrel outcome as a single line for the install summary.
 */
export function formatBarrelOutcome(
  outcome: BarrelOutcome,
  cwd: string,
  dryRun: boolean,
): string | null {
  if (outcome.kind === 'disabled') return null;
  if (outcome.kind === 'skipped-foreign') {
    return (
      `barrel: skipped — ${relative(cwd, outcome.path)} exists but wasn't ` +
      `created by the CLI. Delete it to let \`ondajs add\` manage one, ` +
      `or pass --no-barrel to silence this warning.`
    );
  }
  const verb = dryRun
    ? outcome.kind === 'written'
      ? 'would write'
      : 'unchanged'
    : outcome.kind === 'written'
      ? 'wrote'
      : 'unchanged';
  const cCount = outcome.componentCount;
  const tCount = outcome.transitionCount;
  const cLabel = `${cCount} component${cCount === 1 ? '' : 's'}`;
  const tLabel = tCount > 0 ? `, ${tCount} transition${tCount === 1 ? '' : 's'}` : '';
  return `barrel: ${verb}  ${relative(cwd, outcome.path)}  (${cLabel}${tLabel})`;
}
